### ISSUE TITLE
[Docker frontend] Optimizare

### ISSUE THREAD

**Issue by andrei-dracea** [BanatIT/oxigen#2]
Ma intreb daca nu putem sa optimizam Dockerfile daca omitem pasul de `COPY`, ceva de genul

```
FROM node:lts-alpine as build-stage

RUN apk add git
WORKDIR /app/frontend

RUN yarn
RUN yarn build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

**Comment by vtemian** [comment]
Din pacate e nevoie pentru a copia codul sursa si pe urma build pentru el.
In cazul de mai sus, `yarn build` nu are la ce sa faca build.

Putem in schimb sa ignoram anumite fisiere de care nu avem nevoie, in `.dockerignore`.
Ar trebui ignorat oricum `node_modules` si `dist`. Cumva au ajuns astea 2 directoare pe live si build-ul mergea cu versiuni vechi de dependinte.

**Comment by andrei-dracea** [comment]
ok, dar daca punem `WORKDIR /app/frontend` nu se rezolva? :)

**Comment by vtemian** [comment]
Din pacate nu pentru ca `WORKDIR` doar o sa creeze directorul si o sa mute contextul curent in el. 
Cred ca cel mai ok ar fi sa facem build-ul in github action si in deploy, doar sa facem un docker pull si un restart.
Putem sa paralelizam si build-ul si ar relativ putin.

**Comment by andrei-dracea** [comment]
am inteles. atunci putem rula `yarn --cwd ./frontend/ install` respectiv `yarn --cwd ./frontend/ build`, should also do the trick

**Comment by andrei-dracea** [comment]
> Ar trebui ignorat oricum `node_modules` si `dist`. Cumva au ajuns astea 2 directoare pe live si build-ul mergea cu versiuni vechi de dependinte.

nu stiu daca inteleg, in `.gitignore` sunt puse

**Comment by costibleotu** [comment]
@vtemian nu are legatura cu volumul facut ?

**Comment by andrei-dracea** [comment]
@vtemian imi poti te rog explica cum ai rezolvat problema? a aparut din nou cu acest boilerplate si in alt proiect

**Comment by vtemian** [comment]
> am inteles. atunci putem rula `yarn --cwd ./frontend/ install` respectiv `yarn --cwd ./frontend/ build`, should also do the trick

Nu prea merge fara `COPY . /frontend`, pentru ca nu ai la ce sa faci build, pana ce nu ai sursele in container.

> > Ar trebui ignorat oricum `node_modules` si `dist`. Cumva au ajuns astea 2 directoare pe live si build-ul mergea cu versiuni vechi de dependinte.
> 
> nu stiu daca inteleg, in `.gitignore` sunt puse

Da, `.gitignore` ignora fisierele si directoarele in git. `.dockerignore` are exact acelasi comportament, dar pentru comenzile `COPY/ADD` din `Dockerfile`. Daca facem build-ul pe server (ceea ce ar trebui schimbat), ar trebui ignorate `node_modules` si `dist` la copierea in container (pentru ca s-ar putea sa ai stale data de la alte build-uri).



> @vtemian nu are legatura cu volumul facut ?
Volumul facut e doar pentru fisierele media si e montant in api https://github.com/BanatIT/oxigen/blob/master/production.yml#L23


> @vtemian imi poti te rog explica cum ai rezolvat problema? a aparut din nou cu acest boilerplate si in alt proiect

Practic dar am sters `node_modules` si `dist` de pe server. Trebuie puse in `.dockerignore` ca sa rezolvam de tot problema, fara carpeala.

**Comment by andrei-dracea** [comment]
ok, eu am ajuns sa rulez `docker-compose exec node yarn` ca sa actualizeze pachetele pentru local dev, altfel nu merge
